# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto1',
            name='d',
            field=models.CharField(default='America/Recife', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto1',
            name='nome2',
            field=models.CharField(default='America/Recife', max_length=200),
            preserve_default=False,
        ),
    ]
